###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql57:
      image: mysql:5.7
      container_name: user-crud-test-mysql-57
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=user_crud_test
        - MYSQL_USER=user_crud_test
        - MYSQL_PASSWORD=123456
      ports:
        - "8086:3306"
      networks:
        - mynet

    webserver:
      image: nginx:alpine
      container_name: user-crud-test-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8084:80"
      networks:
        - mynet

    php-fpm:
      build: phpdocker/php-fpm
      container_name: user-crud-test-php-fpm
      working_dir: /application
      environment:
        - DB_HOST=mysql57
        - DB_PORT=3306
        - DB_DATABASE=user_crud_test
        - DB_USERNAME=user_crud_test
        - DB_PASSWORD=123456
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      networks:
        - mynet

networks:
  mynet:
    driver: bridge